title: Group 14
subtitle: a 3400 team
theme: jekyll-theme-cayman
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}
