theme: jekyll-theme-minimal
title: "Group 14"
description: "Thursday Lab with the team members: Giacomo Di Liberto, Joan Song, Kristina Nemeth, Russell Silva, Michelle Feng"
{{ https://kristinanemeth.github.io/group14/ }}/blob/master/Group 14 Team Contract (1).pdf
