theme: jekyll-theme-minimal
title: "Group 14"
description: "Thursday Lab with the team members: Giacomo Di Liberto, Joan Song, Kristina Nemeth, Russell Silva, Michelle Feng"
{{kristinanemeth.github.io }}/blob/master/Group 14 Team Contract (1).pdf
